# Site settings
title: Health IT Conferences
email: noranda@norandabrown.com
description: > # this means to ignore newlines until "baseurl:"
  An open source list for health IT, design, and development conferences.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://noranda.github.io/health-it-conferences" # the base hostname & protocol for your site
twitter_username: noranda82
github_username:  noranda
future: true

# Build settings
markdown: kramdown

permalink: conferences/:year/:month/:day/:title.html

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Rakefile
  - README.md
  - vendor

sass:
  sass_dir: _scss
  style: :compressed
